### ISSUE TITLE
about pretrain weight

### ISSUE THREAD

**Issue by frreason** [sejong-rcv/INSANet#1]
Hello, could you please release your pre training weights on the LLVIP dataset?

**Comment by childult-programmer** [comment]
Thank you for your interest in our research.

1. Unfortunately, we only organize our code for KAIST datasets and due to other environment dependencies reasons, we no longer have access to the experiment code about the LLVIP dataset. We apologize for any inconvenience.

2. To alleviate any inconvenience, we have attached a link containing the files we configured for training on the LLVIP dataset and our detection results file (INSANet_LLVIP_test_det.txt). Feel free to ask about related to reimplementation. [LLVIP](https://drive.google.com/file/d/1LbLkjCNIwoHYT3pD_9LN7bWiKlvfzTxj/view?usp=sharing)

**Comment by frreason** [comment]
Thank you for your reply!



***@***.***
 
From: silee
Date: 2024-04-23 09:40
To: sejong-rcv/INSANet
CC: frreason; Author
Subject: Re: [sejong-rcv/INSANet] about pretrain weight (Issue #1)
Thank you for your interest in our research.
Unfortunately, we only organize our code for KAIST datasets and due to other environment dependencies reasons, we no longer have access to the experiment code about the LLVIP dataset. We apologize for any inconvenience.
To alleviate any inconvenience, we have attached a link containing the files we configured for training on the LLVIP dataset and our detection results file (INSANet_LLVIP_test_det.txt). Feel free to ask about related to reimplementation. LLVIP
