### ISSUE TITLE
I am learning your success, thank you for your team, I have a few questions to ask you, I hope you can take time to reply, thank you very much!

### ISSUE THREAD

**Issue by aitangbodan** [sejong-rcv/INSANet#3]
Q1 : What does conv4_3_feats regularize by multiplying rescale_factors (20)?
![Uploading cacceb33f19e99a7991c0a461ac776a6.png…]()

Q2 : Can you provide data interface for LLVIP? 

Thank you for your reply！

**Comment by childult-programmer** [comment]
Hi, @aitangbodan.

Thank you for your interest and kind words.

Q1. We adopt SSD (Single-Shot MultiBox Detector) as a base architecture. In SSD, since lower-level feature map (conv4_3_feats) have considerably larger scales, take the L2 norm for rescaling. The rescale factor is initially set to 20.

Q2. Can you tell us more about the meaning of "data inference"? Do you mean the inference step? or does it mean setting up the data? If the former, the code used for inference is largely consistent with the setup at KAIST.
