### ISSUE TITLE
Some questions about the number of KAIST training datasets

### ISSUE THREAD

**Issue by Liu-zhi-chao** [sejong-rcv/INSANet#5]
Hello, thank you very much for this excellent research work!
I have some questions about the training dataset of Kaist.
You mentioned in the paper:
```
In the experiment, we follow the standard criterion as train02, which sample frames such that a total of **25,076** images are used for training.
```
But I found a total of **25086** files in src/imageSets/train-all-02.txt in your code.
In addition, you said that you use paired annotations provided in AR-CNN. But I found the number of files in AR-CNN/splits/trainval.txt file in his github repository is **8892**. This is a huge difference from 25086.
So I would like to ask you, which number of annotations should we use as the standard for the unified training dataset?
Thank you for your reply！

**Comment by childult-programmer** [comment]
Thank you for your interest in our research.

We followed and built data from MLPD paper. But now that we've checked, the annotation is correct at **25,086**. You're right.
We use AR-CNN-style annotation, not the annotation lists (trainval.txt). So, if you want to follow a standard commonly used in the Kaist dataset, leverage 25,086 images in training.

We'd like to upload the annotation files for that data ourselves, but we're not sure about copyright issues.

**Comment by Liu-zhi-chao** [comment]
Thank you very much for your reply!

I want to use Yolov8 to implement multispectral pedestrian detection using the KAIST dataset, but I encountered several problems and would like to ask for your help:
Q1: I only use the true value annotation of one modality during training. How should I choose this problem?
Q2: Similar to the AR-CNN method, they did a lot of data cleaning during training and deleted a large number of negative samples of images without pedestrians. Which version of the training dataset should I use as a benchmark?

Thank you for your support and look forward to your reply!

**Comment by childult-programmer** [comment]
_Q1:  I only use the true value annotation of one modality during training. How should I choose this problem?_

Ans: What does it mean, "true value annotation"? Is it mean "only with RGB or Thermal"?
In that case, It's up to performance, because the annotator was annotating based on RGB images, and in the night environment, with the help of thermal images. check the benchmark dataset paper.

_Q2: Similar to the AR-CNN method, they did a lot of data cleaning during training and deleted a large number of negative samples of images without pedestrians. Which version of the training dataset should I use as a benchmark?_

Ans: For benchmarks, we recommend training the entire image, including the negative samples (did you mean background, right?). It is also important for the model to learn the background without objects. but, some frameworks (e.g., detectron2) automatically delete the "background-only images". I think it's also up to performance, but I expect the performance change to be negligible.

**Comment by Liu-zhi-chao** [comment]
Oh, your answer is very helpful to me! When I was looking at the paired annotations of train and improved annotations of test provided by AR-CNN and Liu, I found that there are not only people categories, but also cyclist, person, etc. How do you deal with these categories during training and val? Do you delete them directly or treat them all as people?

**Comment by childult-programmer** [comment]
In data loader, we only deal with the class (person) we want!

**Comment by childult-programmer** [comment]
Reopen if issue persists. Thanks!
